# Generated by Django 5.0.2 on 2024-03-06 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="showCity",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="showDate",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="showName",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="showVenue",
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showName", models.CharField(max_length=255, null=True)),
                ("showVenue", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "showCity",
                    models.CharField(
                        choices=[
                            ("Harare", "Harare"),
                            ("Bulawayo", "Bulawayo"),
                            ("Gweru", "Gweru"),
                            ("Chitungwiza", "Chitungwiza"),
                            ("Mutare", "Mutare"),
                            ("Kwekwe", "Kwekwe"),
                            ("Kadoma", "Kadoma"),
                            ("Masvingo", "Masvingo"),
                            ("Norton", "Norton"),
                            ("Chinhoyi", "Chinhoyi"),
                        ],
                        default="Not Selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("showDate", models.DateTimeField(null=True)),
                ("amount", models.IntegerField(null=True)),
                ("numbertickets", models.IntegerField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tickets.show",
            ),
        ),
    ]
