# Generated by Django 5.0.2 on 2024-03-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_alter_show_created_by_alter_ticket_show"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="show",
            options={"ordering": ["showDate"]},
        ),
        migrations.AlterField(
            model_name="show",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="picture"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="picture"),
        ),
    ]
