# Generated by Django 5.0.2 on 2024-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0005_alter_show_options_alter_show_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pics"),
        ),
    ]
