# Generated by Django 5.0.2 on 2024-03-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0006_alter_show_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
