# Generated by Django 5.0.2 on 2024-03-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0007_alter_show_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="numbertickets",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
