# Generated by Django 5.0.2 on 2024-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stsuser",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bussiness", "Bussiness Account"),
                    ("Personal", "Personal Account"),
                ],
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
