# Generated by Django 5.0.2 on 2024-07-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_stsuser_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stsuser",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bussiness", "Bussiness Account"),
                    ("personal", "Personal Account"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
