# Generated by Django 5.0.2 on 2024-07-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_stsuser_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="national_id",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
