# Generated by Django 5.0.2 on 2024-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_stsuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stsuser",
            name="code",
            field=models.CharField(max_length=7, null=True),
        ),
    ]
