# Generated by Django 5.0.2 on 2024-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="amountPaid",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="numberPeople",
            field=models.IntegerField(null=True),
        ),
    ]
