# Generated by Django 5.0.2 on 2024-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_remove_ticket_showcity_remove_ticket_showdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="amountPaid",
            field=models.DecimalField(decimal_places=2, max_digits=255, null=True),
        ),
    ]
