# Generated by Django 5.0.2 on 2024-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_ticket_amountpaid_alter_ticket_numberpeople"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
