# Generated by Django 5.0.2 on 2024-07-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showName", models.CharField(max_length=255, null=True)),
                ("showVenue", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "showCity",
                    models.CharField(
                        choices=[
                            ("Harare", "Harare"),
                            ("Bulawayo", "Bulawayo"),
                            ("Gweru", "Gweru"),
                            ("Chitungwiza", "Chitungwiza"),
                            ("Mutare", "Mutare"),
                            ("Kwekwe", "Kwekwe"),
                            ("Kadoma", "Kadoma"),
                            ("Masvingo", "Masvingo"),
                            ("Norton", "Norton"),
                            ("Chinhoyi", "Chinhoyi"),
                        ],
                        default="Not Selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("showDate", models.DateTimeField(null=True)),
                ("vip_price", models.IntegerField(blank=True, default=0, null=True)),
                ("vvip_price", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "general_price",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("numbertickets", models.IntegerField(default=0, null=True)),
                ("picture", models.ImageField(blank=True, null=True, upload_to="pics")),
            ],
            options={
                "ordering": ["showDate"],
            },
        ),
    ]
