# Generated by Django 5.0.2 on 2024-07-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
