# Generated by Django 5.0.2 on 2024-07-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0002_show_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="created_on",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="show",
            name="showDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="show",
            name="updated_on",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
