# Generated by Django 5.0.2 on 2024-03-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
